[project]
name = "opencatalyst-garden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "ase>=3.24.0",
    "modal>=0.73.21",
    "torch>=2.4.0",
]

[tool.uv]
dev-dependencies = [
    "ipython>=8.32.0",
]
