[project]
name = "opencatalyst-garden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ase>=3.24.0",
    "modal>=0.73.15",
    "numpy>=2.2.2",
    "torch>=2.6.0",
]
